schema_version = "1.0.0"

id = "surge"
name = "SURGE"
version = "1.0.0"
tagline = "Generate surf ramps for SurfsUp and Godot"
maintainer = "bearlikelion (Mark)"

type = "add-on"

website = "https://github.com/SurfsUpGame/SURGE"

tags = ["Mesh", "Object", "Game Engine"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.*",
  "/docs/",
  "/tests/",
  "/*.zip",
]
